const photo = "https://avatar.iran.liara.run/public";

export const facultyData = [
  {
    id: 1,
    name: "Dr. Kuldeep Pundlik Waidya",
    designation: "Principal",
    qualification: "M. Pharm., Ph.D.",
    dateOfJoining: "2024-01-01",
    experience: "17 years",
    email: "kpwaidya@gmail.com",
    mobile: "8983232009",
    photo: photo,
  },
  {
    id: 2,
    name: "Ms. Shifa Rafique Shikalgar",
    designation: "Vice Principal",
    qualification: "M. Pharmacy (Pharmaceutics)",
    dateOfJoining: "2022-10-01",
    experience: "6 years",
    email: "ssr.smkvpcop@gmail.com",
    mobile: "8999521024",
    photo: photo,
  },
  {
    id: 3,
    name: "Ms. Ashwini Nandkumar Gadage",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Quality Assurance Technique)",
    dateOfJoining: "2022-10-01",
    experience: "3 years",
    email: "ang.smkvpcop@gmail.com",
    mobile: "7057848048",
    photo: photo,
  },
  {
    id: 4,
    name: "Ms. Reshma Dilip Pawar",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Pharmacology)",
    dateOfJoining: "2023-01-25",
    experience: "3 years",
    email: "reshmapawar579@gmail.com",
    mobile: "9096251204",
    photo: photo,
  },
  {
    id: 5,
    name: "Ms. Shiba Dilawar Shaikh",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Pharmaceutics)",
    dateOfJoining: "2019-07-01",
    experience: "6 years",
    email: "ssd.smkvpcop@gmail.com",
    mobile: "7741081606",
    photo: photo,
  },
  {
    id: 6,
    name: "Ms. Chaskar Archana Tukaram",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Pharmaceutical Chemistry)",
    dateOfJoining: "2024-01-15",
    experience: "6 years",
    email: "archanachaskar12@gmail.com",
    mobile: "9503822674",
    photo: photo,
  },
  {
    id: 7,
    name: "Ms. Jagruti Ramesh Salve",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Pharmacology)",
    dateOfJoining: "2022-08-17",
    experience: "3 years",
    email: "jrs.smkvpcop@gmail.com",
    mobile: "9579172245",
    photo: photo,
  },
  {
    id: 8,
    name: "Miss. Gosavi Akshata Anil",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Pharmaceutics)",
    dateOfJoining: "2024-10-01",
    experience: "1 year",
    email: "gosaviakshata3460@gmail.com",
    mobile: "9373736541",
    photo: photo,
  },
  {
    id: 9,
    name: "Miss. Moghe Shital Rajkumar",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Pharmacology)",
    dateOfJoining: "2024-10-01",
    experience: "1 year",
    email: "shitalmoghe1@gmail.com",
    mobile: "7558391544",
    photo: photo,
  },
  {
    id: 10,
    name: "Miss. Bhor Vaishnavi Ramesh",
    designation: "Assistant Professor",
    qualification: "M. Pharmacy (Quality Assurance)",
    dateOfJoining: "2024-10-01",
    experience: "1 year",
    email: "vrbsmkvp@gmail.com",
    mobile: "7387733422",
    photo: photo,
  },
  {
    id: 11,
    name: "Mrs. Nanda Dattatray Ratnaparakhi",
    designation: "Librarian",
    qualification: "M. Lib.",
    dateOfJoining: "2012-08-01",
    experience: "12 years",
    email: "ndr.smkvpcop@gmail.com",
    mobile: "9175819172",
    photo: photo,
  },
  {
    id: 12,
    name: "Ms. Kiran Sunil Langhe",
    designation: "Lecturer",
    qualification: "B. Pharmacy",
    dateOfJoining: "2022-08-17",
    experience: "3 years",
    email: "lk.smkvpcop@gmail.com",
    mobile: "7620381138",
    photo: photo,
  },
  {
    id: 13,
    name: "Ms. Supriya Ashok Gawade",
    designation: "Lecturer",
    qualification: "B. Pharmacy",
    dateOfJoining: "2023-01-17",
    experience: "2 years",
    email: "sag.smkvpcop2023@gmail.com",
    mobile: "7719082505",
    photo: photo,
  },
  {
    id: 14,
    name: "Ms. Akanksha Balaso Kumbhar",
    designation: "Lecturer",
    qualification: "B. Pharmacy",
    dateOfJoining: "2023-12-11",
    experience: "1 year",
    email: "akankshtakumbhar09@gmail.com",
    mobile: "7744903936",
    photo: photo,
  },
  {
    id: 15,
    name: "Ms. Ichake Nilam Vitthal",
    designation: "Lecturer",
    qualification: "B. Pharmacy",
    dateOfJoining: "2024-10-01",
    experience: "1 year",
    email: "nilamichake64@gmail.com",
    mobile: "7378859010",
    photo: photo,
  },
];
