export const nonTeachingStaffData = [
  {
    id: 1,
    name: "Kishor Appasaheb Harde",
    qualification: "HSC",
    mobile: "9921155035",
    designation: "Laboratory Assistant / Attender",
    dateOfJoining: "2023-01-02",
    photo: "https://example.com/images/kishor_harde.jpg",
  },
  {
    id: 2,
    name: "Vishakha Vikas Thorat",
    qualification: "HSC",
    mobile: "8180801632",
    designation: "Laboratory Assistant / Attender",
    dateOfJoining: "2017-07-01",
    photo: "https://example.com/images/vishakha_thorat.jpg",
  },
  {
    id: 3,
    name: "Sachin Yashvant Jadhav",
    qualification: "D. Pharmacy",
    mobile: "8421740939",
    designation: "Laboratory Technician",
    dateOfJoining: "2016-08-01",
    photo: "https://example.com/images/sachin_jadhav.jpg",
  },
  {
    id: 4,
    name: "Amol Ramesh Kale",
    qualification: "SSC",
    mobile: "7498193308",
    designation: "Gardener",
    dateOfJoining: "2023-01-02",
    photo: "https://example.com/images/amol_kale.jpg",
  },
  {
    id: 5,
    name: "Rajaram Popat Dhawale",
    qualification: "SSC",
    mobile: "9767093560",
    designation: "Peon",
    dateOfJoining: "2011-08-01",
    photo: "https://example.com/images/rajaram_dhawale.jpg",
  },
  {
    id: 6,
    name: "Supekar Santosh Bhausaheb",
    qualification: "B.A",
    mobile: "7588694806",
    designation: "Accountant",
    dateOfJoining: "2010-08-02",
    photo: "https://example.com/images/santosh_supekar.jpg",
  },
  {
    id: 7,
    name: "Dilip Eknath Kawade",
    qualification: "HSC",
    mobile: "9011609666",
    designation: "Office Staff I",
    dateOfJoining: "2016-08-01",
    photo: "https://example.com/images/dilip_kawade.jpg",
  },
  {
    id: 8,
    name: "Mukesh Yashwant Pawar",
    qualification: "SSC",
    mobile: "9022350130",
    designation: "Peon",
    dateOfJoining: "2019-09-02",
    photo: "https://example.com/images/mukesh_pawar.jpg",
  },
  {
    id: 9,
    name: "Neema Santosh Supekar",
    qualification: "D. Pharmacy",
    mobile: "7588694806",
    designation: "Store Keeper",
    dateOfJoining: "2016-08-01",
    photo: "https://example.com/images/neema_supekar.jpg",
  },
  {
    id: 10,
    name: "Monika Mukesh Pawar",
    qualification: "SSC",
    mobile: "9022350130",
    designation: "Cleaning Personnel",
    dateOfJoining: "2023-01-02",
    photo: "https://example.com/images/monika_pawar.jpg",
  },
  {
    id: 11,
    name: "Rahul Babaji Auti",
    qualification: "B. Com",
    mobile: "9403645056",
    designation: "Office Staff II",
    dateOfJoining: "2023-01-02",
    photo: "https://example.com/images/rahul_auti.jpg",
  },
  {
    id: 12,
    name: "Poonam Sandip Idhate",
    qualification: "BA ADTT",
    mobile: "9766333390",
    designation: "Computer Data Operator",
    dateOfJoining: "2016-08-01",
    photo: "https://example.com/images/poonam_idhate.jpg",
  },
  {
    id: 13,
    name: "Pipada Kamalesh Vilas",
    qualification: "B.Sc",
    mobile: "9860772277",
    designation: "Office Superintendent",
    dateOfJoining: "2010-08-02",
    photo: "https://example.com/images/kamalesh_pipada.jpg",
  },
  {
    id: 14,
    name: "Neeta Rajendra Jathar",
    qualification: "D. Pharmacy",
    mobile: "9307529051",
    designation: "Laboratory Technician",
    dateOfJoining: "2023-01-02",
    photo: "https://example.com/images/neeta_jathar.jpg",
  },
  {
    id: 15,
    name: "Gandhakte Kanchan Shivaji",
    qualification: "D. Pharmacy",
    mobile: "9067961596",
    designation: "Laboratory Technician",
    dateOfJoining: "2023-01-02",
    photo: "https://example.com/images/kanchan_gandhakte.jpg",
  },
  {
    id: 16,
    name: "Kate Ashwini Ganesh",
    qualification: "HSC",
    mobile: "9307892613",
    designation: "Laboratory Assistant / Attender",
    dateOfJoining: "2023-01-02",
    photo: "https://example.com/images/ashwini_kate.jpg",
  },
  {
    id: 17,
    name: "Sandip Pandurang Idhate",
    qualification: "D. Pharmacy",
    mobile: "9766333390",
    designation: "Laboratory Technician",
    dateOfJoining: "2016-08-01",
    photo: "https://example.com/images/sandip_idhate.jpg",
  },
];
